### ISSUE TITLE
La section qui se nomme section est blanche

### ISSUE THREAD

**Issue by GuyliannEngels** [AliceM2000/AliceM_Blog#1]
Salut @AliceM2000 ,

Sur ton blog, on peut observer que tu as éditer la bannière de ton blog. La couleur est sympa. Cependant, ta section qui se nomme `Sections` reste blanche ce qui est dommage.

J'ai un solution pour toi. Dans ton fichier `style.css` ajoute les instructions suivantes

```
nav-dropdown .nav-dropbtn {
  color: purple;
}

.nav-dropdown:hover .nav-dropbtn {
    color: white;
  }
```

**Comment by AliceM2000** [comment]
Bonsoir,

J'ai essayé les instructions comme vous me l'avez demandé mais ça ne marche pas quand je build
La section reste blanche

Merci d'avoir jeté un coup d'œil dans mon blog

Bien à vous

Alice Marin
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : mardi 3 novembre 2020 13:33
À : AliceM2000/AliceM_Blog <AliceM_Blog@noreply.github.com>
Cc : Alice MARIN <Alice.MARIN@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : [AliceM2000/AliceM_Blog] La section qui se nomme section est blanche (#1)


Salut @AliceM2000<https://github.com/AliceM2000> ,

Sur ton blog, on peut observer que tu as éditer la bannière de ton blog. La couleur est sympa. Cependant, ta section qui se nomme Sections reste blanche ce qui est dommage.

J'ai un solution pour toi. Dans ton fichier style.css ajoute les instructions suivantes

nav-dropdown .nav-dropbtn {

  color: purple;

}



.nav-dropdown:hover .nav-dropbtn {

    color: white;

  }

**Comment by GuyliannEngels** [comment]
J'ai réalisé un pull request pour t'aider ;)
